"""echo-cli init — scaffold a new model project."""
from pathlib import Path

import click
from rich.console import Console

console = Console()

TEMPLATE = '''"""
{class_name} — Echo quant model.

Generated by `echo-cli init`. Edit me to implement your alpha.
"""
from echo_quant import Model, Inputs, Signal, zscore

class {class_name}(Model):
    model_id = "{model_id}"
    asset = "{asset}"
    version = "v0.1.0"
    category = "factor"
    description = "TODO: describe your model."

    @classmethod
    def required_data(cls):
        return ["ohlcv_1h"]

    def predict(self, inputs: Inputs) -> Signal:
        closes = [bar.close for bar in inputs.ohlcv_1h]
        if len(closes) < 24:
            return Signal(
                asset=inputs.asset,
                direction="neutral",
                edge_bps=0.0,
                expected_vol_bps=80.0,
            )

        # Example: mean-reversion on 24h z-score
        z = zscore(closes, window=24)
        if z > 2.0:
            return Signal(
                asset=inputs.asset,
                direction="short",
                edge_bps=10.0 * abs(z),
                expected_vol_bps=80.0,
                confidence=min(0.5 + abs(z) * 0.1, 0.95),
            )
        elif z < -2.0:
            return Signal(
                asset=inputs.asset,
                direction="long",
                edge_bps=10.0 * abs(z),
                expected_vol_bps=80.0,
                confidence=min(0.5 + abs(z) * 0.1, 0.95),
            )
        return Signal(
            asset=inputs.asset,
            direction="neutral",
            edge_bps=0.0,
            expected_vol_bps=80.0,
        )
'''

@click.command("init")
@click.argument("model_id")
@click.option("--asset", default="ETH", help="Primary asset (BTC, ETH, SOL, ...)")
@click.option("--dir", "output_dir", default=".", help="Output directory")
def cmd(model_id: str, asset: str, output_dir: str):
    """Scaffold a new model: echo-cli init my-model-id"""
    out = Path(output_dir).resolve()
    out.mkdir(parents=True, exist_ok=True)

    file_path = out / f"{model_id.replace('-', '_')}.py"
    if file_path.exists():
        console.print(f"[red]File exists:[/red] {file_path}")
        raise SystemExit(1)

    class_name = "".join(part.capitalize() for part in model_id.replace("-", "_").split("_"))
    file_path.write_text(
        TEMPLATE.format(
            class_name=class_name,
            model_id=model_id,
            asset=asset.upper(),
        )
    )
    console.print(f"[green]Created[/green] {file_path}")
    console.print("\nNext steps:")
    console.print(f"  1. Edit [cyan]{file_path.name}[/cyan]")
    console.print(f"  2. [cyan]echo-cli validate {file_path}[/cyan]")
    console.print(f"  3. [cyan]echo-cli backtest {file_path}[/cyan]")
